/*
Magnitude Analysis == Measure by Dimnension

*/

---Total Customer by Country

select * from dim_customers limit 5 ;

select
country,
count (distinct customer_id) as Total_customer
from dim_customers
group by country
order by Total_customer desc

--Total customer by Gender :

select
Gender,
count (distinct customer_id) as Total_customer
from dim_customers
group by Gender
order by Total_customer desc

--Total Product by Category :

select * from dim_products dp  limit 5;

select 
category,
count (product_key) as total_product
from dim_products
Group by category
order by total_product desc


--Average cost of Each department


select 
category,
AVG (cost) as Average_cost
from dim_products
Group by category
order by Average_cost desc


--Total Revenue generated by each product ;

select * from fact_sales fs limit 5;
select * from dim_products  limit 5 ;
select * from dim_customers limit 5;

select 
p.category,
sum (s.sales_amount)  as sales

from fact_sales s 
left join dim_products p 
On  s.product_key = p.product_key 
group by category
ORDER BY sales DESC

--Total Revenue genertated by each customers : 

select 
s.customer_key,
c.last_name,
c.first_name,
sum (s.sales_amount) as Sales
from  fact_sales s 
left join dim_customers c  on s.customer_key =c.customer_key 
group by 
c.customer_id,
c.last_name,
c.first_name
order by Sales desc


--- Distribution of sold items Across countries :

select 
 c.country,
 sum (s.sales_amount) as sales 
 from  fact_sales s 
left join dim_customers c  on s.customer_key =c.customer_key 
group by c.country
order by sales desc


